import cv2
import imutils
from collections import OrderedDict
from constants import constants
from helpers.helper import Helper

cams = OrderedDict({(i,cv2.VideoCapture(i)) for i in range(0,2)})
frames = OrderedDict()
grabbed = OrderedDict()
helper = None

init = False

while True:
    # check all video capture device is it opened or not
    for i, c in cams.items():
        if c is not None and c.isOpened():
            grabbed[i], frames[i] = c.read()

    # initialize the cams that we're using and delete the non-using ones
    if len(constants.cams_in_use) == 0:
        constants.cams_in_use = [i for i,_ in frames.items() if grabbed[i] is True]
        to_be_deleted = []
        for i in cams.keys():
            if i not in constants.cams_in_use:
                to_be_deleted.append(i)
        for i in to_be_deleted: del cams[i]

    # pre-process for the grabbed frames
    for i in constants.cams_in_use:
        if grabbed[i]:
            frames[i] = imutils.resize(frames[i], width=640)
            frames[i] = cv2.flip(frames[i], 1)
            if helper is None:
                h, w, _ = frames[i].shape
                helper = Helper(width=w, height=h)
    if not init:
        # initialize the ordered dicts in the constants module
        constants.initialize()
        # initialize the centroid tracker
        constants.ct.initialize()
        init = True
    # register the recognized staffs and show their bounding boxes
    helper.show_recognized_faces(frames)

    # show on the screen yolo bounding boxes that are generated by the pre-trained yolo head model
    helper.show_yolo_bboxes(frames)

    # track staffs by using detected faces and detected heads centroids
    helper.track()
    
    # draw the screen borders in white color, put room id and time variables as a text on the screen
    helper.draw_to_screen()

    # concatenate all frames then show all cams streams on the screen
    cv2.imshow('Image', helper.get_concatenated_frames())

    constants.clear_ordered_dicts()
    if cv2.waitKey(10) & 0xFF == ord('q'):
        break

# release all cams
helper.release_cams(cams.values())
cv2.destroyAllWindows()
